### ISSUE TITLE
add option to add graphQL operation name to the URL

### ISSUE THREAD

**Issue by tsiq-clemens** [testingisdocumenting/webtau#773]
All graphQL URLs look alike: `/graphql`. It is a big help to have the distinctive `operationName` in the URL as a query param, turning the URL into something like this: `/graphql?operation=doMyLaundry` which would show up in steps, logs, etc. and add tremendous value for developers (I have first-hand experienced with and without this param).

The `operation` query parameter is ignored by all implementations I know, but we can make it optional, e.g. offer a config param `graphQLDoNotShowOperation` or some such.

**Comment by MykolaGolubyev** [comment]
I believe @tsiq-karold created a similar #583 issue. 
Steps is a good point. Even if we have a dedicated graphql tab,  steps would still be lacking. But I think #605 should address those. 
I can help with report one since it will take longer for you to get to the whole dev setup. 
And you can prioritize #605 then.
How does it sound?

**Comment by tsiq-karold** [comment]
Those issues you linked are about improving visibility/debugging *within* webtau.  Appending it to the URL will also help with server side visibility/debugging where logs, for example, often will have URLs but not bodies.

**Comment by MykolaGolubyev** [comment]
I see. We have HttpConigurations that can update url at runtime. Maybe you can use that one? Or implement similar one for GraphQL?

**Comment by tsiq-clemens** [comment]
Can a `HttpConfiguration` help us here, since the operation comes from the `GraphQLRequest`?

**Comment by MykolaGolubyev** [comment]
`HttpConfiguration` will still be called for graphql calls. The problem is probably going to be that at that time you won't know the operation name unless you store it somewhere in thread local context. 
But if we introduce `GraphQLHttpConfiguration` or something like this that will have an extra context, than you could amend each request as you see fit. 

At this point I think that adding `operation=myOperation` to core logic of every graphql call could be confusing to users. Hence proposing to figure out an extension point that you can leverage. 

It could be a switch flag also in a config. 

To double check, if two issues mentioned above are resolved, will you still benefit from adding `operation` param to each call?

**Comment by tsiq-karold** [comment]
> To double check, if two issues mentioned above are resolved, will you still benefit from adding operation param to each call?

Yes, we will because those two issues only help within the context of webtau. The main benefit of appending to the url is to help debugging server side.

I agree that making the url construction pluggable (directly or indirectly) and is a better option than having the appending be a core feature of webtau. I don't think many users would be interested in that specifically.

**Comment by MykolaGolubyev** [comment]
Who is going to take a stab at it ;) ?

**Comment by tsiq-clemens** [comment]
I'm interested in learning more about how these `HttpConfiguration`s work, I can poke it.

**Comment by tsiq-clemens** [comment]
any particular commit prefix for webtau-graphql? Got a PR coming up.
