### ISSUE TITLE
Is there an option to proxy the network traffic while running the test case

### ISSUE THREAD

**Issue by andsus** [testingisdocumenting/webtau#948]
I want to check if webtau can be configured with proxy server for security monitoring for example.
The idea is to have a proxy server like owasp zap to monitor the http traffic while running the webtau test case.

Greatly appreciated if you have example to share.

**Comment by MykolaGolubyev** [comment]
Ah, the PR is hanging there for a while now as I needed proxy as well. And then our infra changed.
Sounds like a good use case to actually land it. 

Are you using groovy or Java version?

**Comment by andsus** [comment]
I'm mainly using groovy. 
Other test framework like calypso and many other js test framework have the proxy config support.

**Comment by andsus** [comment]
I hope the PR can be promoted. 
Is there an option, that I can contribute?

**Comment by MykolaGolubyev** [comment]
Makes sense. Reason I asked about Java, is that there you could set proxy using system property during test run - as a workaround.
I am switching to that PR to revive it and merge. 
Thank you for proposing help. 

One thing that can be helpful is if you could later build webtau from master to confirm that it works for your case - so that I don't release a patch after the release. 
It is OK if it is not something you are comfortable with.

**Comment by andsus** [comment]
Sure, I can run maven build from master webtau master no problem.
And thanks for the pro-tip of using java proxy 
Running java -Djava.net.useSystemProxies=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8800 ... should do the trick?

**Comment by MykolaGolubyev** [comment]
I think so, you can hack webtau shell script and try

**Comment by MykolaGolubyev** [comment]
Please let me know if system properties worked. 

Also, just in case - if you have any questions or suggestions - I will be happy to listen and answer. 
this will help me improve documentation and get ideas for additional features.

**Comment by MykolaGolubyev** [comment]
https://testingisdocumenting.org/webtau/HTTP/proxy
